package it.polimi.ingsw.PSP23.model;

/**
 *
 */
public enum Phase {
    GOD_CHOOSE, GOD_PICK, WORKER_HOUSING,
    START_TURN, CHOOSE_WORKER, CHECK_LOSE_MOVE, CHECK_LOSE_BUILD, CHECK_WIN_MOVE, CHECK_WIN_BUILD, CHECK_WIN, MOVE, BUILD, END
}
